#!/bin/bash

ln -fs ~/.dotfiles/bashrc ~/.bashrc
ln -fs ~/.dotfiles/profile ~/.profile
ln -fs ~/.dotfiles/vimrc ~/.vimrc
ln -fs ~/.dotfiles/tmux.conf ~/.tmux.conf
ln -fs ~/.dotfiles/inputrc ~/.inputrc
ln -fs ~/.dotfiles/editorconfig ~/.editorconfig
ln -fs ~/.dotfiles/gitconfig ~/.gitconfig
ln -fs ~/.dotfiles/gitignore_global ~/.gitignore_global
ln -fs ~/.dotfiles/vim ~/.vim

source ~/.bashrc
install

export PATH="/Users/marcelofelix/.rbenv/shims:${PATH}"
source /usr/local/Cellar/rbenv/0.4.0/completions/rbenv.bash
source /usr/local/etc/bash_completion.d/git-completion.bash

